project:
  type: book
  output-dir: docs

book:
  title: "Análisis de redes en R"
  subtitle: "Un enfoque práctico y didáctico"
  author: 
  - name: Roberto Alvarez
    url: https://sites.google.com/view/robertolvarezmartinez/página-principal
    open-graph: true
    twitter-card:
      creator: "@alvarezrobertoc"
      card-style: summary_large_image
    orcid: 0000-0002-0821-0067
    email: roberto.alvarez@uaq.mx
    affiliations:
      - name: Laboratorio de Biología Cuantitativa y Sistemas Complejos, Universidad Autónoma de Querétaro
        address: Campus Aeropuerto
        city: Querétaro
        state: Querétaro
        postal-code: 76261
  date: today
  language: es
  search: true
  repo-actions: [edit]
  sidebar:
    style: docked
    search: true
  chapters:
    - index.qmd
    - 01-fundamentos-igraph.qmd
    - 02-grado-distribuciones.qmd
    - 03-distancias-eficiencia.qmd
    - 04-clustering.qmd
    - 05-robustez.qmd
    - 06-centralidad.qmd
    - 07-comunidades.qmd
    - 08-Visnetworks.qmd
    - 99-ejercicios-integradores.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    code-line-numbers: true
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    callout-appearance: simple
    fig-align: center
    fig-responsive: true
    df-print: kable
    smooth-scroll: true
  pdf:
    documentclass: scrreprt
    papersize: letter
    code-block-bg: "#f5f5f5"
    code-block-border-left: "#3ABEF9"
    fig-pos: "H"
    tbl-pos: "H"
    number-sections: true
    colorlinks: true

execute:
  echo: true
  warning: false
  message: false
  fig-width: 13
  fig-height: 8
